/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pos.mvc.view;

import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import pos.mvc.controller.CustomerController;
import pos.mvc.model.CustomerModel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Damith
 */
public class CustomerView extends javax.swing.JFrame {

    private CustomerController customerController;

    /**
     * Creates new form CustomerView
     */
    public CustomerView() {
        this.customerController = new CustomerController();
        initComponents();
        loadAllCustomers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        basePanel = new javax.swing.JPanel();
        formPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        customerIDLabel = new javax.swing.JLabel();
        customerIdField = new javax.swing.JTextField();
        customerTitleLabel = new javax.swing.JLabel();
        customerTitleField = new javax.swing.JTextField();
        customerAddressField = new javax.swing.JTextField();
        customerAddressLabel = new javax.swing.JLabel();
        custemerNameFiled = new javax.swing.JTextField();
        customerNameLabel = new javax.swing.JLabel();
        customerDOBField = new javax.swing.JTextField();
        customerDOBLabel = new javax.swing.JLabel();
        customerCityLabel = new javax.swing.JLabel();
        customerCityField = new javax.swing.JTextField();
        customerProvinceLabel = new javax.swing.JLabel();
        customerProvinceField = new javax.swing.JTextField();
        customerPostalCodeField = new javax.swing.JTextField();
        customerPostalCodeLabel = new javax.swing.JLabel();
        createCustomerButton = new javax.swing.JButton();
        deleteCustomerButton = new javax.swing.JButton();
        updateCustomerButton = new javax.swing.JButton();
        customerZipCodeField = new javax.swing.JTextField();
        customerSalaryLabel = new javax.swing.JLabel();
        customerSalaryField = new javax.swing.JTextField();
        customerZipCodeLabel = new javax.swing.JLabel();
        customerDataView = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        basePanel.setName("Manager Customer"); // NOI18N

        headerLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("Manager Customer");

        customerIDLabel.setText("Customer ID");

        customerIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerIdFieldActionPerformed(evt);
            }
        });

        customerTitleLabel.setText("Customer Title");

        customerTitleField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerTitleFieldActionPerformed(evt);
            }
        });

        customerAddressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerAddressFieldActionPerformed(evt);
            }
        });

        customerAddressLabel.setText("Address");

        custemerNameFiled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custemerNameFiledActionPerformed(evt);
            }
        });

        customerNameLabel.setText("Customer Name");

        customerDOBField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerDOBFieldActionPerformed(evt);
            }
        });

        customerDOBLabel.setText("Customer DOB");

        customerCityLabel.setText("City");

        customerCityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerCityFieldActionPerformed(evt);
            }
        });

        customerProvinceLabel.setText("Proovince");
        customerProvinceLabel.setToolTipText("");

        customerProvinceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerProvinceFieldActionPerformed(evt);
            }
        });

        customerPostalCodeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerPostalCodeFieldActionPerformed(evt);
            }
        });

        customerPostalCodeLabel.setText("Postal Code");

        createCustomerButton.setText("Save Customer");
        createCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCustomerButtonActionPerformed(evt);
            }
        });

        deleteCustomerButton.setText("Delete Customer");
        deleteCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCustomerButtonActionPerformed(evt);
            }
        });

        updateCustomerButton.setText("Update Customer");
        updateCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCustomerButtonActionPerformed(evt);
            }
        });

        customerZipCodeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerZipCodeFieldActionPerformed(evt);
            }
        });

        customerSalaryLabel.setText("Salary");

        customerSalaryField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerSalaryFieldActionPerformed(evt);
            }
        });

        customerZipCodeLabel.setText("Zip Code");
        customerZipCodeLabel.setToolTipText("");

        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        customerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(customerTable);

        javax.swing.GroupLayout customerDataViewLayout = new javax.swing.GroupLayout(customerDataView);
        customerDataView.setLayout(customerDataViewLayout);
        customerDataViewLayout.setHorizontalGroup(
            customerDataViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerDataViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
                .addContainerGap())
        );
        customerDataViewLayout.setVerticalGroup(
            customerDataViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerDataViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout formPanelLayout = new javax.swing.GroupLayout(formPanel);
        formPanel.setLayout(formPanelLayout);
        formPanelLayout.setHorizontalGroup(
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formPanelLayout.createSequentialGroup()
                        .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(headerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(formPanelLayout.createSequentialGroup()
                                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(formPanelLayout.createSequentialGroup()
                                            .addComponent(deleteCustomerButton)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(updateCustomerButton)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(createCustomerButton)
                                            .addGap(6, 6, 6))
                                        .addGroup(formPanelLayout.createSequentialGroup()
                                            .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(formPanelLayout.createSequentialGroup()
                                                    .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(customerTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(customerCityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(46, 46, 46))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, formPanelLayout.createSequentialGroup()
                                                    .addComponent(customerAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                            .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(formPanelLayout.createSequentialGroup()
                                                    .addComponent(customerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(34, 34, 34)
                                                    .addComponent(custemerNameFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(customerAddressField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(formPanelLayout.createSequentialGroup()
                                                        .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, formPanelLayout.createSequentialGroup()
                                                                .addComponent(customerPostalCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(customerZipCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(formPanelLayout.createSequentialGroup()
                                                                .addComponent(customerCityField, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(customerProvinceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(formPanelLayout.createSequentialGroup()
                                                                .addComponent(customerTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(customerDOBLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGap(34, 34, 34)
                                                        .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(customerDOBField, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(customerProvinceField, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(customerZipCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addComponent(customerSalaryField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(formPanelLayout.createSequentialGroup()
                                        .addComponent(customerIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)
                                        .addComponent(customerIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(formPanelLayout.createSequentialGroup()
                        .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customerPostalCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerSalaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerDataView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 51, Short.MAX_VALUE))))
        );
        formPanelLayout.setVerticalGroup(
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerIDLabel)
                    .addComponent(customerIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerNameLabel)
                    .addComponent(custemerNameFiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerTitleLabel)
                    .addComponent(customerTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerDOBLabel)
                    .addComponent(customerDOBField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerCityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerProvinceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerProvinceLabel)
                    .addComponent(customerCityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customerPostalCodeLabel)
                    .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(customerPostalCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(customerZipCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(customerZipCodeLabel)))
                .addGap(17, 17, 17)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerSalaryLabel)
                    .addComponent(customerSalaryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(customerDataView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createCustomerButton)
                    .addComponent(updateCustomerButton)
                    .addComponent(deleteCustomerButton))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout basePanelLayout = new javax.swing.GroupLayout(basePanel);
        basePanel.setLayout(basePanelLayout);
        basePanelLayout.setHorizontalGroup(
            basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        basePanelLayout.setVerticalGroup(
            basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(basePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customerIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerIdFieldActionPerformed

    private void customerTitleFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerTitleFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerTitleFieldActionPerformed

    private void customerAddressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerAddressFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerAddressFieldActionPerformed

    private void custemerNameFiledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custemerNameFiledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custemerNameFiledActionPerformed

    private void customerDOBFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerDOBFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerDOBFieldActionPerformed

    private void customerCityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerCityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerCityFieldActionPerformed

    private void customerProvinceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerProvinceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerProvinceFieldActionPerformed

    private void customerPostalCodeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerPostalCodeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerPostalCodeFieldActionPerformed

    private void deleteCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCustomerButtonActionPerformed
        deleteCustomer();
    }//GEN-LAST:event_deleteCustomerButtonActionPerformed

    private void createCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCustomerButtonActionPerformed
        saveCustomerData();
    }//GEN-LAST:event_createCustomerButtonActionPerformed

    private void customerZipCodeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerZipCodeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerZipCodeFieldActionPerformed

    private void customerSalaryFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerSalaryFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerSalaryFieldActionPerformed

    private void customerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerTableMouseClicked
        searchParicularCustomer();
    }//GEN-LAST:event_customerTableMouseClicked

    private void updateCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCustomerButtonActionPerformed
        this.updateCustomer();
    }//GEN-LAST:event_updateCustomerButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel basePanel;
    private javax.swing.JButton createCustomerButton;
    private javax.swing.JTextField custemerNameFiled;
    private javax.swing.JTextField customerAddressField;
    private javax.swing.JLabel customerAddressLabel;
    private javax.swing.JTextField customerCityField;
    private javax.swing.JLabel customerCityLabel;
    private javax.swing.JTextField customerDOBField;
    private javax.swing.JLabel customerDOBLabel;
    private javax.swing.JPanel customerDataView;
    private javax.swing.JLabel customerIDLabel;
    private javax.swing.JTextField customerIdField;
    private javax.swing.JLabel customerNameLabel;
    private javax.swing.JTextField customerPostalCodeField;
    private javax.swing.JLabel customerPostalCodeLabel;
    private javax.swing.JTextField customerProvinceField;
    private javax.swing.JLabel customerProvinceLabel;
    private javax.swing.JTextField customerSalaryField;
    private javax.swing.JLabel customerSalaryLabel;
    private javax.swing.JTable customerTable;
    private javax.swing.JTextField customerTitleField;
    private javax.swing.JLabel customerTitleLabel;
    private javax.swing.JTextField customerZipCodeField;
    private javax.swing.JLabel customerZipCodeLabel;
    private javax.swing.JButton deleteCustomerButton;
    private javax.swing.JPanel formPanel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton updateCustomerButton;
    // End of variables declaration//GEN-END:variables

    /**
     * save customer data
     */
    private void saveCustomerData() {
        CustomerModel customerModel = new CustomerModel(customerIdField.getText(),
                customerTitleField.getText(),
                custemerNameFiled.getText(),
                customerDOBField.getText(),
                Double.parseDouble(customerSalaryField.getText()),
                customerAddressField.getText(),
                customerCityField.getText(),
                customerProvinceField.getText(),
                customerZipCodeField.getText());

        try {
            String resp = customerController.saveCustomer(customerModel);
            JOptionPane.showMessageDialog(this, resp);
            clear();
            loadAllCustomers();
        } catch (SQLException ex) {
            Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    /**
     * clear customer form data
     */
    private void clear() {
        customerIdField.setText("");
        customerTitleField.setText("");
        custemerNameFiled.setText("");
        customerDOBField.setText("");
        customerSalaryField.setText("");
        customerAddressField.setText("");
        customerCityField.setText("");
        customerProvinceField.setText("");
        customerZipCodeField.setText("");
    }

    /**
     * load existing customers
     */
    private void loadAllCustomers() {

        try {
            String[] collumns = {"Id", "Name", "Address", "Salary", "Postal Code"};
            DefaultTableModel dtm = new DefaultTableModel(collumns, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
            customerTable.setModel(dtm);

            ArrayList<CustomerModel> customers = customerController.getAllCustomers();

            for (CustomerModel customer : customers) {
                Object[] rowData = {customer.getCustId(), customer.getTitle() + " " + customer.getName(), customer.getAddress() + ", " + customer.getCity(), customer.getSalary(), customer.getZip()};
                dtm.addRow(rowData);
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    /**
     * search paricular customer using id
     */
    private void searchParicularCustomer() {
        try {
            String custId = customerTable.getValueAt(customerTable.getSelectedRow(), 0).toString();
            CustomerModel customerModel = customerController.getCustomerById(custId);

            if (customerModel != null) {
                customerIdField.setText(customerModel.getCustId());
                customerTitleField.setText(customerModel.getTitle());
                custemerNameFiled.setText(customerModel.getName());
                customerDOBField.setText(customerModel.getDob());
                customerSalaryField.setText(Double.toString(customerModel.getSalary()));
                customerAddressField.setText(customerModel.getAddress());
                customerCityField.setText(customerModel.getCity());
                customerProvinceField.setText(customerModel.getProvince());
                customerZipCodeField.setText(customerModel.getZip());
            } else {
                JOptionPane.showMessageDialog(this, "Customer Not Found");
            }

        } catch (SQLException ex) {
            Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    /**
     * update customer
     */
    public void updateCustomer() {
        try {
            CustomerModel customer = new CustomerModel(
                    customerIdField.getText(),
                    customerTitleField.getText(),
                    custemerNameFiled.getText(),
                    customerDOBField.getText(),
                    Double.parseDouble(customerSalaryField.getText()),
                    customerAddressField.getText(),
                    customerCityField.getText(),
                    customerProvinceField.getText(),
                    customerZipCodeField.getText());

            String resp = customerController.updateCustomer(customer);
            JOptionPane.showMessageDialog(this, resp);
            clear();
            loadAllCustomers();
        } catch (SQLException ex) {
            Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * delete customers
     */
    private void deleteCustomer() {
        try {
            String custId = customerTable.getValueAt(customerTable.getSelectedRow(), 0).toString();
            String resp = customerController.deleteCustomer(custId);
            clear();
            loadAllCustomers();
            JOptionPane.showMessageDialog(this, resp);
        } catch (SQLException ex) {
            Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

    }
}
